# Streamlit Community Cloud deployment configuration

[server]
headless = true
enableCORS = false


[theme]
primaryColor = "#4F8BF9"
backgroundColor = "#000000ff"
secondaryBackgroundColor = "#161616ff"
textColor = "#ffffffff"
font = "sans serif"
